# Generated by Django 3.2.16 on 2022-11-04 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='social_network',
            field=models.URLField(verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True,
                                       verbose_name='Дата дедлайна'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=True, max_length=400, verbose_name='Описание'),
        ),
    ]
