# Generated by Django 3.2.16 on 2022-11-07 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0002_auto_20221104_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнение'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                       verbose_name='Дата дедлайна'),
        ),
    ]
